name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore **/*.csproj
    - name: Build
      run: dotnet build --no-restore -c Release **/*.csproj
    - name: Test
      run: dotnet test -c Release --no-build --no-restore --verbosity normal **/*Tests.csproj
    - name: Pack
      run: dotnet pack -v normal -c Release --no-restore --include-symbols --no-build -p:PackageVersion=$GITHUB_RUN_ID !**/*Tests.csproj
    - name: Publish Nuget to GitHub registry
      run: dotnet nuget push "**/*.nupkg" -k ${NUGET_TOKEN} -s https://api.nuget.org/v3/index.json --skip-duplicate
      env:
        NUGET_TOKEN: ${{ secrets.NUGET_KEY }}
